### PR TITLE
Armhf support?

### PR DESCRIPTION
**Pull request by RedstoneWizard08**

### CODE REVIEW

**Comment by RedstoneWizard08** [comment]
Mentioning this run: https://github.com/RedstoneWizard08/bitnami-compat/actions/runs/1821189108

**Comment by RedstoneWizard08** [comment]
I'm updating bitnami minideb with support for arm64

**Comment by ZCube** [comment]
@RedstoneWizard08 There are packages that only provide arm64 binaries. So it seems difficult to pull it right now. As you know, the minideb image does not support armhf. The way the platform is chosen as a whole is therefore difficult to agree on. It would be better to select a possible platform for each Docker image.

**Comment by ZCube** [comment]
The ideal method seems to be to record the platforms supported by each package, and to calculate and use the platforms supported by the included packages at the time of build.

**Comment by ZCube** [comment]
@RedstoneWizard08 There is also no armhf package in https://archive.mariadb.org/mariadb-10.6.5/repo/debian/pool/main/m/mariadb-10.6/ , http://apt.postgresql.org/pub/repos/apt/dists/buster-pgdg/15/. For now, this PR will stop many builds. Currently, there is a problem with using these packages in armhf. Nevertheless, if you want to support armhf, you should choose to support armhf selectively rather than using it for all images.

**Comment by RedstoneWizard08** [comment]
Okay.

**Pull request closed without merging**
